<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\Witeem.McpServer.Application.Contracts\Witeem.McpServer.Application.Contracts.csproj" />
    <ProjectReference Include="..\Witeem.McpServer.McpServer\Witeem.McpServer.McpServer.csproj" />
    <PackageReference Include="Volo.Abp.AspNetCore.Mvc" Version="$(AbpFrameworkVersion)" />
  </ItemGroup>
</Project>
